---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ngsa-mem-dev
  namespace: joaquin-dev
  annotations:
    fluxcd.io/automated: "true"
    #filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: ngsa-mem-dev
  chart:
    git: git@github.com:joaquinrz/ngsa-flux
    path: charts/ngsa
    ref: main
  values:
    image:
      repository: joaquinrodriguez/ngsa
      tag: beta
    ingress:
      hosts:
        - ngsa-mem-dev.cse.ms
    paths:
      - /
    app:
      args: [["--in-memory"]]
      region: "West"
      zone: "Az-WestUS2"
    cert:
      name: ngsa-cert
